# languages.py
LANGUAGES = {
    "fr": {
        "title": "Téléchargeur YouTube",
        "enter_links": "Entrez les liens (un par ligne) :",
        "load_formats": "Charger résolutions",
        "download_type": "Type de téléchargement :",
        "video": "Vidéo",
        "audio": "Audio",
        "resolution": "Résolution :",
        "start_download": "Lancer le téléchargement",
        "language": "Langue",
        "status": "Statut :",
        "choose_folder": "Dossier de sortie",
        "select_folder": "Sélectionner un dossier",
        "no_links": "Aucun lien fourni.",
        "no_format": "Aucun format sélectionné.",
        "formats_loaded": "Résolutions chargées.",
        "loading_formats": "Chargement des résolutions...",
        "download_finished": "Téléchargement terminé.",
        "download_started": "Téléchargement démarré.",
        "error": "Erreur :"
    },
    "en": {
        "title": "YouTube Downloader",
        "enter_links": "Enter links (one per line):",
        "load_formats": "Load resolutions",
        "download_type": "Download type:",
        "video": "Video",
        "audio": "Audio",
        "resolution": "Resolution:",
        "start_download": "Start Download",
        "language": "Language",
        "status": "Status:",
        "choose_folder": "Output folder",
        "select_folder": "Select a folder",
        "no_links": "No links provided.",
        "no_format": "No format selected.",
        "formats_loaded": "Resolutions loaded.",
        "loading_formats": "Loading resolutions...",
        "download_finished": "Download finished.",
        "download_started": "Download started.",
        "error": "Error:"
    }
}
